// 06_physics_collision.c - Decompiled from stbc.exe
// Generated by decompile_all.py


// ====== 0x005c7030  FUN_005c7030 ======
undefined4 * __thiscall FUN_005c7030(void *this,int param_1)

{
  FUN_006d5c00(this,param_1);
  *(undefined ***)this = &PTR_FUN_0089451c;
  *(undefined2 *)((int)this + 0x28) = 0;
  return (undefined4 *)this;
}

// ====== 0x005c70c0  FUN_005c70c0 ======
int * __thiscall FUN_005c70c0(void *this,byte param_1)

{
  void *this_00;
  int *piVar1;
  
  thunk_FUN_006d5d70((undefined4 *)this);
  if ((param_1 & 1) != 0) {
    piVar1 = (int *)this;
    this_00 = (void *)FUN_00717b20(0x2c);
    FUN_00718180(this_00,piVar1);
  }
  return (int *)this;
}

// ====== 0x005c70f0  thunk_FUN_006d5d70 ======
void __fastcall thunk_FUN_006d5d70(undefined4 *param_1)

{
  int iVar1;
  void *pvStack_c;
  undefined1 *puStack_8;
  undefined4 uStack_4;
  
  puStack_8 = &LAB_0087e8d8;
  pvStack_c = ExceptionList;
  ExceptionList = &pvStack_c;
  *param_1 = &PTR_FUN_00895ff4;
  uStack_4 = 0;
  FUN_006d6480((int)param_1);
  iVar1 = param_1[2];
  param_1[4] = 0;
  if ((iVar1 != 0) && (param_1[3] != iVar1)) {
    FUN_006d5a80(iVar1);
  }
  iVar1 = param_1[3];
  param_1[2] = 0;
  if ((iVar1 != 0) && (iVar1 != DAT_0095adfc)) {
    FUN_006d5a80(iVar1);
  }
  param_1[3] = 0;
  param_1[5] = 0xbf800000;
  *(undefined2 *)(param_1 + 6) = 0;
  *(undefined2 *)((int)param_1 + 0x1a) = 0;
  param_1[9] = 0;
  uStack_4 = 0xffffffff;
  FUN_006f0ba0(param_1);
  ExceptionList = pvStack_c;
  return;
}

// ====== 0x005c7c50  FUN_005c7c50 ======
undefined4 * __thiscall FUN_005c7c50(void *this,int param_1)

{
  FUN_006d5c00(this,param_1);
  *(undefined ***)this = &PTR_FUN_00894558;
  *(undefined4 *)((int)this + 0x28) = 0;
  return (undefined4 *)this;
}

// ====== 0x005c7d00  FUN_005c7d00 ======
int * __thiscall FUN_005c7d00(void *this,byte param_1)

{
  void *this_00;
  int *piVar1;
  
  thunk_FUN_006d5d70((undefined4 *)this);
  if ((param_1 & 1) != 0) {
    piVar1 = (int *)this;
    this_00 = (void *)FUN_00717b20(0x2c);
    FUN_00718180(this_00,piVar1);
  }
  return (int *)this;
}

// ====== 0x005c7d30  thunk_FUN_006d5d70 ======
void __fastcall thunk_FUN_006d5d70(undefined4 *param_1)

{
  int iVar1;
  void *pvStack_c;
  undefined1 *puStack_8;
  undefined4 uStack_4;
  
  puStack_8 = &LAB_0087e8d8;
  pvStack_c = ExceptionList;
  ExceptionList = &pvStack_c;
  *param_1 = &PTR_FUN_00895ff4;
  uStack_4 = 0;
  FUN_006d6480((int)param_1);
  iVar1 = param_1[2];
  param_1[4] = 0;
  if ((iVar1 != 0) && (param_1[3] != iVar1)) {
    FUN_006d5a80(iVar1);
  }
  iVar1 = param_1[3];
  param_1[2] = 0;
  if ((iVar1 != 0) && (iVar1 != DAT_0095adfc)) {
    FUN_006d5a80(iVar1);
  }
  param_1[3] = 0;
  param_1[5] = 0xbf800000;
  *(undefined2 *)(param_1 + 6) = 0;
  *(undefined2 *)((int)param_1 + 0x1a) = 0;
  param_1[9] = 0;
  uStack_4 = 0xffffffff;
  FUN_006f0ba0(param_1);
  ExceptionList = pvStack_c;
  return;
}

// ====== 0x005c9530  FUN_005c9530 ======
undefined4 * __fastcall FUN_005c9530(undefined4 *param_1)

{
  FUN_006d5c00(param_1,0);
  *(ushort *)(param_1 + 6) = *(ushort *)(param_1 + 6) & 0xff;
  *param_1 = &PTR_FUN_00894594;
  return param_1;
}

// ====== 0x005c95c0  FUN_005c95c0 ======
int * __thiscall FUN_005c95c0(void *this,byte param_1)

{
  void *this_00;
  int *piVar1;
  
  thunk_FUN_006d5d70((undefined4 *)this);
  if ((param_1 & 1) != 0) {
    piVar1 = (int *)this;
    this_00 = (void *)FUN_00717b20(0x28);
    FUN_00718180(this_00,piVar1);
  }
  return (int *)this;
}

// ====== 0x005c95f0  thunk_FUN_006d5d70 ======
void __fastcall thunk_FUN_006d5d70(undefined4 *param_1)

{
  int iVar1;
  void *pvStack_c;
  undefined1 *puStack_8;
  undefined4 uStack_4;
  
  puStack_8 = &LAB_0087e8d8;
  pvStack_c = ExceptionList;
  ExceptionList = &pvStack_c;
  *param_1 = &PTR_FUN_00895ff4;
  uStack_4 = 0;
  FUN_006d6480((int)param_1);
  iVar1 = param_1[2];
  param_1[4] = 0;
  if ((iVar1 != 0) && (param_1[3] != iVar1)) {
    FUN_006d5a80(iVar1);
  }
  iVar1 = param_1[3];
  param_1[2] = 0;
  if ((iVar1 != 0) && (iVar1 != DAT_0095adfc)) {
    FUN_006d5a80(iVar1);
  }
  param_1[3] = 0;
  param_1[5] = 0xbf800000;
  *(undefined2 *)(param_1 + 6) = 0;
  *(undefined2 *)((int)param_1 + 0x1a) = 0;
  param_1[9] = 0;
  uStack_4 = 0xffffffff;
  FUN_006f0ba0(param_1);
  ExceptionList = pvStack_c;
  return;
}

// ====== 0x005c97c0  FUN_005c97c0 ======
undefined4 * __fastcall FUN_005c97c0(undefined4 *param_1)

{
  FUN_006d5c00(param_1,0);
  *(ushort *)(param_1 + 6) = *(ushort *)(param_1 + 6) & 0xff;
  *param_1 = &PTR_FUN_008945d0;
  param_1[4] = 0x30001;
  return param_1;
}

// ====== 0x005c9870  FUN_005c9870 ======
int * __thiscall FUN_005c9870(void *this,byte param_1)

{
  void *this_00;
  int *piVar1;
  
  thunk_FUN_006d5d70((undefined4 *)this);
  if ((param_1 & 1) != 0) {
    piVar1 = (int *)this;
    this_00 = (void *)FUN_00717b20(0x30);
    FUN_00718180(this_00,piVar1);
  }
  return (int *)this;
}

// ====== 0x005c98a0  thunk_FUN_006d5d70 ======
void __fastcall thunk_FUN_006d5d70(undefined4 *param_1)

{
  int iVar1;
  void *pvStack_c;
  undefined1 *puStack_8;
  undefined4 uStack_4;
  
  puStack_8 = &LAB_0087e8d8;
  pvStack_c = ExceptionList;
  ExceptionList = &pvStack_c;
  *param_1 = &PTR_FUN_00895ff4;
  uStack_4 = 0;
  FUN_006d6480((int)param_1);
  iVar1 = param_1[2];
  param_1[4] = 0;
  if ((iVar1 != 0) && (param_1[3] != iVar1)) {
    FUN_006d5a80(iVar1);
  }
  iVar1 = param_1[3];
  param_1[2] = 0;
  if ((iVar1 != 0) && (iVar1 != DAT_0095adfc)) {
    FUN_006d5a80(iVar1);
  }
  param_1[3] = 0;
  param_1[5] = 0xbf800000;
  *(undefined2 *)(param_1 + 6) = 0;
  *(undefined2 *)((int)param_1 + 0x1a) = 0;
  param_1[9] = 0;
  uStack_4 = 0xffffffff;
  FUN_006f0ba0(param_1);
  ExceptionList = pvStack_c;
  return;
}

// ====== 0x005c9a00  FUN_005c9a00 ======
undefined4 * __thiscall FUN_005c9a00(void *this,undefined4 *param_1,ushort param_2)

{
  FUN_006d5c00(this,0);
  *(ushort *)((int)this + 0x18) = *(ushort *)((int)this + 0x18) & 0xff;
  *(undefined ***)this = &PTR_FUN_008945d0;
  *(undefined4 *)((int)this + 0x10) = 0x30001;
  *(undefined4 *)((int)this + 0x28) = *param_1;
  *(undefined4 *)((int)this + 0x2c) = param_1[1];
  *(ushort *)((int)this + 0x18) = *(ushort *)((int)this + 0x18) | param_2 & 0xff00;
  return (undefined4 *)this;
}

// ====== 0x005c9df0  FUN_005c9df0 ======
undefined4 * __thiscall
FUN_005c9df0(void *this,undefined4 param_1,undefined4 param_2,undefined4 param_3)

{
  FUN_006d5c00(this,0);
  *(ushort *)((int)this + 0x18) = *(ushort *)((int)this + 0x18) & 0xff;
  *(undefined4 *)((int)this + 0x28) = param_1;
  *(undefined ***)this = &PTR_FUN_0089460c;
  *(undefined4 *)((int)this + 0x10) = 0x30002;
  *(undefined4 *)((int)this + 0x2c) = param_2;
  *(undefined4 *)((int)this + 0x30) = param_3;
  return (undefined4 *)this;
}

// ====== 0x005c9eb0  FUN_005c9eb0 ======
int * __thiscall FUN_005c9eb0(void *this,byte param_1)

{
  void *this_00;
  int *piVar1;
  
  thunk_FUN_006d5d70((undefined4 *)this);
  if ((param_1 & 1) != 0) {
    piVar1 = (int *)this;
    this_00 = (void *)FUN_00717b20(0x34);
    FUN_00718180(this_00,piVar1);
  }
  return (int *)this;
}

// ====== 0x005c9ee0  thunk_FUN_006d5d70 ======
void __fastcall thunk_FUN_006d5d70(undefined4 *param_1)

{
  int iVar1;
  void *pvStack_c;
  undefined1 *puStack_8;
  undefined4 uStack_4;
  
  puStack_8 = &LAB_0087e8d8;
  pvStack_c = ExceptionList;
  ExceptionList = &pvStack_c;
  *param_1 = &PTR_FUN_00895ff4;
  uStack_4 = 0;
  FUN_006d6480((int)param_1);
  iVar1 = param_1[2];
  param_1[4] = 0;
  if ((iVar1 != 0) && (param_1[3] != iVar1)) {
    FUN_006d5a80(iVar1);
  }
  iVar1 = param_1[3];
  param_1[2] = 0;
  if ((iVar1 != 0) && (iVar1 != DAT_0095adfc)) {
    FUN_006d5a80(iVar1);
  }
  param_1[3] = 0;
  param_1[5] = 0xbf800000;
  *(undefined2 *)(param_1 + 6) = 0;
  *(undefined2 *)((int)param_1 + 0x1a) = 0;
  param_1[9] = 0;
  uStack_4 = 0xffffffff;
  FUN_006f0ba0(param_1);
  ExceptionList = pvStack_c;
  return;
}

// ====== 0x005c9f50  FUN_005c9f50 ======
undefined4 * __fastcall FUN_005c9f50(undefined4 *param_1)

{
  FUN_006d5c00(param_1,0);
  *(ushort *)(param_1 + 6) = *(ushort *)(param_1 + 6) & 0xff;
  *param_1 = &PTR_FUN_0089460c;
  param_1[4] = 0x30002;
  return param_1;
}

// ====== 0x005ca3a0  FUN_005ca3a0 ======
undefined4 * __fastcall FUN_005ca3a0(undefined4 *param_1)

{
  FUN_006d5c00(param_1,0);
  *(ushort *)(param_1 + 6) = *(ushort *)(param_1 + 6) & 0xff;
  param_1[0xb] = 0;
  param_1[0xd] = 0;
  param_1[0xc] = 0;
  param_1[10] = 0;
  *param_1 = &PTR_FUN_00894648;
  param_1[4] = 0x30003;
  return param_1;
}

// ====== 0x005ca450  FUN_005ca450 ======
int * __thiscall FUN_005ca450(void *this,byte param_1)

{
  void *this_00;
  int *piVar1;
  
  thunk_FUN_006d5d70((undefined4 *)this);
  if ((param_1 & 1) != 0) {
    piVar1 = (int *)this;
    this_00 = (void *)FUN_00717b20(0x38);
    FUN_00718180(this_00,piVar1);
  }
  return (int *)this;
}

// ====== 0x005ca480  thunk_FUN_006d5d70 ======
void __fastcall thunk_FUN_006d5d70(undefined4 *param_1)

{
  int iVar1;
  void *pvStack_c;
  undefined1 *puStack_8;
  undefined4 uStack_4;
  
  puStack_8 = &LAB_0087e8d8;
  pvStack_c = ExceptionList;
  ExceptionList = &pvStack_c;
  *param_1 = &PTR_FUN_00895ff4;
  uStack_4 = 0;
  FUN_006d6480((int)param_1);
  iVar1 = param_1[2];
  param_1[4] = 0;
  if ((iVar1 != 0) && (param_1[3] != iVar1)) {
    FUN_006d5a80(iVar1);
  }
  iVar1 = param_1[3];
  param_1[2] = 0;
  if ((iVar1 != 0) && (iVar1 != DAT_0095adfc)) {
    FUN_006d5a80(iVar1);
  }
  param_1[3] = 0;
  param_1[5] = 0xbf800000;
  *(undefined2 *)(param_1 + 6) = 0;
  *(undefined2 *)((int)param_1 + 0x1a) = 0;
  param_1[9] = 0;
  uStack_4 = 0xffffffff;
  FUN_006f0ba0(param_1);
  ExceptionList = pvStack_c;
  return;
}

// ====== 0x005cb6a0  FUN_005cb6a0 ======
/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

void * __cdecl FUN_005cb6a0(void *param_1)

{
  float fVar1;
  float10 extraout_ST1;
  float10 extraout_ST1_00;
  longlong lVar2;
  float local_1c;
  float local_18;
  float local_14;
  float local_10;
  void *local_c;
  undefined1 *puStack_8;
  uint local_4;
  
  local_4 = 0xffffffff;
  puStack_8 = &LAB_0087baff;
  local_c = ExceptionList;
  ExceptionList = &local_c;
  FUN_00739db0(&local_1c);
  fVar1 = _DAT_0099d24c;
  local_4 = 1;
  lVar2 = __ftol();
  if ((int)lVar2 == 0) {
    local_1c = 0.0;
  }
  else {
    local_1c = (float)((float10)(int)lVar2 / extraout_ST1);
  }
  lVar2 = __ftol();
  if ((int)lVar2 == 0) {
    local_18 = 0.0;
  }
  else {
    local_18 = (float)(int)lVar2 / fVar1;
  }
  lVar2 = __ftol();
  if ((int)lVar2 == 0) {
    local_14 = 0.0;
  }
  else {
    local_14 = (float)((float10)(int)lVar2 / extraout_ST1_00);
  }
  lVar2 = __ftol();
  if ((int)lVar2 == 0) {
    local_10 = 0.0;
  }
  else {
    local_10 = (float)(int)lVar2 / fVar1;
  }
  FUN_00739dc0(param_1,&local_1c);
  local_4 = local_4 & 0xffffff00;
  FUN_00739e20();
  ExceptionList = local_c;
  return param_1;
}

// ====== 0x005d1440  FUN_005d1440 ======
undefined4 * __cdecl FUN_005d1440(char *param_1,undefined4 param_2)

{
  ushort *puVar1;
  void *this;
  undefined4 *puVar2;
  undefined4 local_1c [4];
  void *local_c;
  undefined1 *puStack_8;
  undefined4 local_4;
  
  local_4 = 0xffffffff;
  puStack_8 = &LAB_0087bb27;
  local_c = ExceptionList;
  ExceptionList = &local_c;
  puVar1 = (ushort *)FUN_00717b70(0x7c);
  this = (void *)FUN_00718010(puVar1);
  if (this == (void *)0x0) {
    puVar2 = (undefined4 *)0x0;
  }
  else {
    puVar2 = (undefined4 *)FUN_00739db0(local_1c);
    local_4 = 0;
    puVar2 = FUN_00741660(this,param_1,param_2,puVar2,0x3f800000,0);
  }
  local_4 = 0xffffffff;
  if (this != (void *)0x0) {
    FUN_00739e20();
  }
  ExceptionList = local_c;
  return puVar2;
}

// ====== 0x005d1910  FUN_005d1910 ======
void * __thiscall FUN_005d1910(void *this,void *param_1)

{
  FUN_00739dc0(param_1,(undefined4 *)((int)this + 0x58));
  return param_1;
}

// ====== 0x005d1930  FUN_005d1930 ======
int * FUN_005d1930(undefined4 param_1,undefined4 *param_2)

{
  int iVar1;
  undefined4 *puVar2;
  int *piVar3;
  
  iVar1 = FUN_0074e310(param_2,(byte *)s_O_TGFrame_GetNiColor_00934aec);
  if (iVar1 == 0) {
    return (int *)0x0;
  }
  iVar1 = FUN_005bae00((int *)0x0,(int *)&param_2,DAT_0099113c,1);
  if (iVar1 == -1) {
    return (int *)0x0;
  }
  puVar2 = (undefined4 *)FUN_00718cb0(0x10);
  if (puVar2 != (undefined4 *)0x0) {
    *puVar2 = param_2[0x1a];
    puVar2[1] = param_2[0x1b];
    puVar2[2] = param_2[0x1c];
    puVar2[3] = param_2[0x1d];
    piVar3 = FUN_005bb0e0((uint)puVar2,DAT_009911f4);
    return piVar3;
  }
  piVar3 = FUN_005bb0e0(0,DAT_009911f4);
  return piVar3;
}

// ====== 0x005d47c0  FUN_005d47c0 ======
void __thiscall FUN_005d47c0(void *this,char *param_1)

{
  undefined1 local_1c [8];
  void *pvStack_14;
  void *pvStack_c;
  undefined1 *puStack_8;
  undefined4 local_4;
  
  local_4 = 0xffffffff;
  puStack_8 = &LAB_0087bb48;
  pvStack_c = ExceptionList;
  ExceptionList = &pvStack_c;
  FUN_006f3e90(local_1c,param_1);
                    /* WARNING: Load size is inaccurate */
  local_4 = 0;
  (**(code **)(*this + 0x15c))(local_1c);
  pvStack_c = (void *)0xffffffff;
  FUN_006f3ef0((int)&stack0xffffffdc);
  ExceptionList = pvStack_14;
  return;
}

// ====== 0x005d4900  FUN_005d4900 ======
void __thiscall FUN_005d4900(void *this,char *param_1)

{
  undefined1 local_1c [8];
  void *pvStack_14;
  void *pvStack_c;
  undefined1 *puStack_8;
  undefined4 local_4;
  
  local_4 = 0xffffffff;
  puStack_8 = &LAB_0087bb68;
  pvStack_c = ExceptionList;
  ExceptionList = &pvStack_c;
  FUN_006f3e90(local_1c,param_1);
                    /* WARNING: Load size is inaccurate */
  *(undefined4 *)((int)this + 0x68) = *(undefined4 *)((int)this + 100);
  local_4 = 0;
  (**(code **)(*this + 0x15c))(local_1c);
  pvStack_c = (void *)0xffffffff;
  FUN_006f3ef0((int)&stack0xffffffdc);
  ExceptionList = pvStack_14;
  return;
}

// ====== 0x005d92f0  FUN_005d92f0 ======
void * __cdecl FUN_005d92f0(char *param_1,char *param_2,uint param_3)

{
  void *pvVar1;
  void *local_c;
  undefined1 *puStack_8;
  undefined4 local_4;
  
  local_4 = 0xffffffff;
  puStack_8 = &LAB_0087bb8b;
  local_c = ExceptionList;
  ExceptionList = &local_c;
  pvVar1 = (void *)FUN_00718cb0(0x98);
  local_4 = 0;
  if (pvVar1 != (void *)0x0) {
    pvVar1 = FUN_0070b030(pvVar1,param_1,param_2,param_3);
    ExceptionList = local_c;
    return pvVar1;
  }
  ExceptionList = local_c;
  return (void *)0x0;
}

// ====== 0x005ddc40  FUN_005ddc40 ======
void __fastcall FUN_005ddc40(int param_1)

{
  void *local_c;
  undefined1 *puStack_8;
  undefined4 local_4;
  
  puStack_8 = &LAB_0087bba8;
  local_c = ExceptionList;
  local_4 = 0;
  ExceptionList = &local_c;
  FUN_006f4ee0((void *)(param_1 + 0xc),&stack0x00000004);
  local_4 = 0xffffffff;
  FUN_006f3ef0((int)&stack0x00000004);
  ExceptionList = local_c;
  return;
}

// ====== 0x005dde50  FUN_005dde50 ======
void __thiscall
FUN_005dde50(void *this,undefined1 param_1,undefined2 *param_2,uint param_3,undefined4 param_4)

{
  uint uVar1;
  undefined4 uVar2;
  undefined2 *puVar3;
  uint uVar4;
  uint uVar5;
  undefined1 local_34 [4];
  undefined2 *local_30;
  uint local_2c;
  undefined4 local_28;
  void *local_c;
  undefined1 *puStack_8;
  undefined4 local_4;
  
  uVar5 = DAT_00888b48;
  puStack_8 = &LAB_0087bbc8;
  local_c = ExceptionList;
  local_4 = 0;
  local_34[0] = param_1;
  local_30 = (undefined2 *)0x0;
  local_2c = 0;
  local_28 = 0;
  uVar4 = param_3;
  if (DAT_00888b48 < param_3) {
    uVar4 = DAT_00888b48;
  }
  if (local_34 == &param_1) {
    ExceptionList = &local_c;
    if (uVar4 != 0) {
      ExceptionList = &local_c;
      FUN_00857f03();
    }
    FUN_00416980(local_34);
    uVar1 = local_2c - uVar4;
    if (uVar1 < uVar5) {
      uVar5 = uVar1;
    }
    if (uVar5 != 0) {
      FUN_0040e360(local_30 + uVar4,local_30 + uVar5 + uVar4,uVar1 - uVar5);
      uVar5 = local_2c - uVar5;
      uVar2 = FUN_00416740(local_34,uVar5,'\0');
      if ((char)uVar2 != '\0') {
        FUN_00416720(local_34,uVar5);
      }
    }
    FUN_00416980(local_34);
  }
  else {
    if ((uVar4 != 0) && (uVar4 == param_3)) {
      puVar3 = param_2;
      if (param_2 == (undefined2 *)0x0) {
        puVar3 = &DAT_00888b44;
      }
      if (*(byte *)((int)puVar3 + -1) < 0xfe) {
        ExceptionList = &local_c;
        FUN_004166d0(local_34,'\x01');
        local_30 = param_2;
        if (param_2 == (undefined2 *)0x0) {
          local_30 = &DAT_00888b44;
        }
        local_2c = param_3;
        local_28 = param_4;
        *(char *)((int)local_30 + -1) = *(char *)((int)local_30 + -1) + '\x01';
        goto LAB_005ddf88;
      }
    }
    ExceptionList = &local_c;
    uVar2 = FUN_00416740(local_34,uVar4,'\x01');
    if ((char)uVar2 != '\0') {
      puVar3 = param_2;
      if (param_2 == (undefined2 *)0x0) {
        puVar3 = &DAT_00888b44;
      }
      FUN_0040e330(local_30,puVar3,uVar4);
      local_30[uVar4] = 0;
      local_2c = uVar4;
    }
  }
LAB_005ddf88:
  FUN_005ddc40((int)this);
  local_4 = 0xffffffff;
  local_28 = 0x5ddfa2;
  FUN_006f3ef0((int)&param_1);
  ExceptionList = local_c;
  return;
}

// ====== 0x005dea10  FUN_005dea10 ======
undefined4 * __fastcall FUN_005dea10(undefined4 *param_1)

{
  undefined4 *puVar1;
  void *local_c;
  undefined1 *puStack_8;
  undefined4 local_4;
  
  local_4 = 0xffffffff;
  puStack_8 = &LAB_0087bbe8;
  local_c = ExceptionList;
  ExceptionList = &local_c;
  FUN_006f0a70(param_1,0);
  local_4 = 0;
  *param_1 = &PTR_FUN_00893d58;
  puVar1 = (undefined4 *)FUN_00718cb0(0x18);
  if (puVar1 != (undefined4 *)0x0) {
    *puVar1 = 0;
    puVar1[1] = 0;
    puVar1[2] = 0;
    puVar1[3] = 0;
    puVar1[4] = 0;
    puVar1[5] = 2;
    param_1[2] = puVar1;
    ExceptionList = local_c;
    return param_1;
  }
  param_1[2] = 0;
  ExceptionList = local_c;
  return param_1;
}

// ====== 0x005e6630  FUN_005e6630 ======
undefined4 * __thiscall FUN_005e6630(void *this,byte param_1)

{
  FUN_005e6650((undefined4 *)this);
  if ((param_1 & 1) != 0) {
    FUN_00718cf0((int)this);
  }
  return (undefined4 *)this;
}

// ====== 0x005e6650  FUN_005e6650 ======
/* WARNING: Removing unreachable block (ram,0x005e66b1) */
/* WARNING: Removing unreachable block (ram,0x005e66b6) */
/* WARNING: Removing unreachable block (ram,0x005e66d6) */

void __fastcall FUN_005e6650(undefined4 *param_1)

{
  int iVar1;
  
  *param_1 = &PTR_FUN_00894684;
  if (param_1[1] != 0) {
    FUN_00718cf0(param_1[1]);
  }
  if (param_1[2] != 0) {
    iVar1 = param_1[3];
    while (0 < iVar1) {
      FUN_00718cf0(*(int *)(param_1[2] + -4 + param_1[3] * 4));
      iVar1 = param_1[3] + -1;
      param_1[3] = iVar1;
    }
    param_1[3] = 0;
    FUN_00718cf0(param_1[2]);
    param_1[2] = 0;
    param_1[4] = 0;
  }
  return;
}

// ====== 0x005ec3d0  FUN_005ec3d0 ======
int * FUN_005ec3d0(undefined4 param_1,undefined4 *param_2)

{
  int iVar1;
  void *pvVar2;
  int *piVar3;
  void *local_4;
  
  iVar1 = FUN_0074e310(param_2,(byte *)s_OO_TGMatrix3_MultMatrixLeft_0093a294);
  if (iVar1 == 0) {
    return (int *)0x0;
  }
  iVar1 = FUN_005bae00((int *)0x0,(int *)&local_4,DAT_0099159c,1);
  if (iVar1 == -1) {
    return (int *)0x0;
  }
  iVar1 = FUN_005bae00((int *)0x0,(int *)&param_2,DAT_0099159c,1);
  if (iVar1 == -1) {
    return (int *)0x0;
  }
  pvVar2 = (void *)FUN_00718cb0(0x24);
  if (pvVar2 != (void *)0x0) {
    pvVar2 = FUN_005ec4a0(local_4,pvVar2,param_2);
    piVar3 = FUN_005bb0e0((uint)pvVar2,DAT_0099159c);
    return piVar3;
  }
  piVar3 = FUN_005bb0e0(0,DAT_0099159c);
  return piVar3;
}

// ====== 0x005e80c0  FUN_005e80c0 ======
undefined4 * __cdecl
FUN_005e80c0(char *param_1,int param_2,undefined4 param_3,undefined4 param_4,undefined4 param_5,
            undefined4 param_6,undefined4 param_7,undefined4 param_8,undefined4 param_9,
            undefined4 param_10)

{
  ushort *puVar1;
  void *this;
  undefined4 *puVar2;
  undefined1 local_1c [16];
  void *local_c;
  undefined1 *puStack_8;
  undefined4 local_4;
  
  local_4 = 0xffffffff;
  puStack_8 = &LAB_0087bc08;
  local_c = ExceptionList;
  ExceptionList = &local_c;
  FUN_006f3e90(local_1c,param_1);
  puVar2 = (undefined4 *)0x0;
  local_4 = 0;
  puVar1 = (ushort *)FUN_00717b70(0x6c);
  this = (void *)FUN_00718010(puVar1);
  if (this != (void *)0x0) {
    puVar2 = FUN_006b1ba0(this,local_1c,param_2,param_3,param_4,param_5,param_6,param_7,param_8,
                          param_9,param_10);
  }
  local_4 = 0xffffffff;
  FUN_006f3ef0((int)local_1c);
  ExceptionList = local_c;
  return puVar2;
}

// ====== 0x005ec4a0  FUN_005ec4a0 ======
void * __thiscall FUN_005ec4a0(void *this,void *param_1,void *param_2)

{
  FUN_00459ad0(param_2,param_1,(float *)this);
  return param_1;
}

// ====== 0x005ec4c0  FUN_005ec4c0 ======
undefined4 FUN_005ec4c0(undefined4 param_1,float *param_2)

{
  int iVar1;
  uint uVar2;
  undefined4 uVar3;
  float *local_10;
  float *local_c;
  void *local_8;
  undefined1 local_4;
  undefined3 uStack_3;
  
  iVar1 = FUN_0074e310(param_2,(byte *)s_OOOO_TGMatrix3_ToEulerAnglesXYZ_0093a2b0);
  if (iVar1 == 0) {
    return 0;
  }
  iVar1 = FUN_005bae00((int *)0x0,(int *)&local_8,DAT_0099159c,1);
  if (iVar1 == -1) {
    return 0;
  }
  iVar1 = FUN_005bae00((int *)0x0,(int *)&local_c,DAT_00991080,1);
  if (iVar1 == -1) {
    return 0;
  }
  iVar1 = FUN_005bae00((int *)0x0,(int *)&local_10,DAT_00991080,1);
  if (iVar1 == -1) {
    return 0;
  }
  iVar1 = FUN_005bae00((int *)0x0,(int *)&param_2,DAT_00991080,1);
  if (iVar1 == -1) {
    return 0;
  }
  uVar2 = FUN_0045ad70(local_8,local_c,local_10,param_2);
  _local_4 = CONCAT31(uStack_3,(char)uVar2);
  uVar3 = FUN_0074c6e0(uVar2 & 0xff);
  return uVar3;
}

// ====== 0x005fcca0  FUN_005fcca0 ======
undefined4 * __thiscall FUN_005fcca0(void *this,byte param_1)

{
  FUN_005fccc0((undefined4 *)this);
  if ((param_1 & 1) != 0) {
    FUN_00718cf0((int)this);
  }
  return (undefined4 *)this;
}

// ====== 0x005fccc0  FUN_005fccc0 ======
void __fastcall FUN_005fccc0(undefined4 *param_1)

{
  *param_1 = &PTR_FUN_00894688;
  FUN_00718cf0(param_1[0xd]);
  FUN_0046f3e0(param_1);
  return;
}
