// 07_audio_input.c - Decompiled from stbc.exe
// Generated by decompile_all.py


// ====== 0x006016c0  FUN_006016c0 ======
undefined1 * __thiscall FUN_006016c0(void *this,undefined1 *param_1)

{
  undefined2 uVar1;
  uint uVar2;
  undefined4 uVar3;
  undefined2 *puVar4;
  undefined2 *puVar5;
  uint uVar6;
  uint uVar7;
  
  *(undefined1 *)this = *param_1;
  *(undefined4 *)((int)this + 4) = 0;
  *(undefined4 *)((int)this + 8) = 0;
  *(undefined4 *)((int)this + 0xc) = 0;
  uVar7 = DAT_00888b48;
  uVar2 = *(uint *)(param_1 + 8);
  uVar6 = uVar2;
  if (DAT_00888b48 < uVar2) {
    uVar6 = DAT_00888b48;
  }
  if ((undefined1 *)this == param_1) {
    if (uVar6 != 0) {
      FUN_00857f03();
    }
    FUN_00416980(this);
    uVar2 = *(int *)((int)this + 8) - uVar6;
    if (uVar2 < uVar7) {
      uVar7 = uVar2;
    }
    if (uVar7 != 0) {
      FUN_0040e360((undefined2 *)(*(int *)((int)this + 4) + uVar6 * 2),
                   (undefined2 *)(*(int *)((int)this + 4) + (uVar7 + uVar6) * 2),uVar2 - uVar7);
      uVar7 = *(int *)((int)this + 8) - uVar7;
      uVar3 = FUN_00416740(this,uVar7,'\0');
      if ((char)uVar3 != '\0') {
        FUN_00416720(this,uVar7);
      }
    }
    FUN_00416980(this);
    return (undefined1 *)this;
  }
  if ((uVar6 != 0) && (uVar6 == uVar2)) {
    puVar4 = *(undefined2 **)(param_1 + 4);
    if (puVar4 == (undefined2 *)0x0) {
      puVar4 = &DAT_00888b44;
    }
    if (*(byte *)((int)puVar4 + -1) < 0xfe) {
      FUN_004166d0(this,'\x01');
      puVar4 = *(undefined2 **)(param_1 + 4);
      if (puVar4 == (undefined2 *)0x0) {
        puVar4 = &DAT_00888b44;
      }
      *(undefined2 **)((int)this + 4) = puVar4;
      *(undefined4 *)((int)this + 8) = *(undefined4 *)(param_1 + 8);
      *(undefined4 *)((int)this + 0xc) = *(undefined4 *)(param_1 + 0xc);
      *(char *)((int)puVar4 + -1) = *(char *)((int)puVar4 + -1) + '\x01';
      return (undefined1 *)this;
    }
  }
  uVar3 = FUN_00416740(this,uVar6,'\x01');
  if ((char)uVar3 != '\0') {
    puVar4 = *(undefined2 **)(param_1 + 4);
    if (puVar4 == (undefined2 *)0x0) {
      puVar4 = &DAT_00888b44;
    }
    puVar5 = *(undefined2 **)((int)this + 4);
    for (uVar2 = uVar6; uVar2 != 0; uVar2 = uVar2 - 1) {
      uVar1 = *puVar4;
      puVar4 = puVar4 + 1;
      *puVar5 = uVar1;
      puVar5 = puVar5 + 1;
    }
    *(uint *)((int)this + 8) = uVar6;
    *(undefined2 *)(*(int *)((int)this + 4) + uVar6 * 2) = 0;
  }
  return (undefined1 *)this;
}

// ====== 0x006043c0  FUN_006043c0 ======
undefined4 * __cdecl FUN_006043c0(int param_1,char *param_2)

{
  void *this;
  undefined4 *puVar1;
  void *local_c;
  undefined1 *puStack_8;
  undefined4 local_4;
  
  local_4 = 0xffffffff;
  puStack_8 = &LAB_0087bc2b;
  local_c = ExceptionList;
  ExceptionList = &local_c;
  this = (void *)FUN_00718cb0(0x40);
  local_4 = 0;
  if (this != (void *)0x0) {
    puVar1 = FUN_0048cc40(this,param_1,param_2);
    ExceptionList = local_c;
    return puVar1;
  }
  ExceptionList = local_c;
  return (undefined4 *)0x0;
}

// ====== 0x00604620  FUN_00604620 ======
undefined4 * __cdecl FUN_00604620(int param_1,char *param_2)

{
  void *this;
  undefined4 *puVar1;
  void *local_c;
  undefined1 *puStack_8;
  undefined4 local_4;
  
  local_4 = 0xffffffff;
  puStack_8 = &LAB_0087bc4b;
  local_c = ExceptionList;
  ExceptionList = &local_c;
  this = (void *)FUN_00718cb0(0x38);
  local_4 = 0;
  if (this != (void *)0x0) {
    puVar1 = FUN_0048fcb0(this,param_1,param_2);
    ExceptionList = local_c;
    return puVar1;
  }
  ExceptionList = local_c;
  return (undefined4 *)0x0;
}

// ====== 0x00604920  FUN_00604920 ======
undefined4 * __cdecl FUN_00604920(int param_1,char *param_2)

{
  void *this;
  undefined4 *puVar1;
  void *local_c;
  undefined1 *puStack_8;
  undefined4 local_4;
  
  local_4 = 0xffffffff;
  puStack_8 = &LAB_0087bc6b;
  local_c = ExceptionList;
  ExceptionList = &local_c;
  this = (void *)FUN_00718cb0(0x40);
  local_4 = 0;
  if (this != (void *)0x0) {
    puVar1 = FUN_004927d0(this,param_1,param_2);
    ExceptionList = local_c;
    return puVar1;
  }
  ExceptionList = local_c;
  return (undefined4 *)0x0;
}

// ====== 0x00604ef0  FUN_00604ef0 ======
undefined4 * __cdecl FUN_00604ef0(int param_1,char *param_2)

{
  void *this;
  undefined4 *puVar1;
  void *local_c;
  undefined1 *puStack_8;
  undefined4 local_4;
  
  local_4 = 0xffffffff;
  puStack_8 = &LAB_0087bc8b;
  local_c = ExceptionList;
  ExceptionList = &local_c;
  this = (void *)FUN_00718cb0(0x40);
  local_4 = 0;
  if (this != (void *)0x0) {
    puVar1 = FUN_00491370(this,param_1,param_2);
    ExceptionList = local_c;
    return puVar1;
  }
  ExceptionList = local_c;
  return (undefined4 *)0x0;
}

// ====== 0x006050c0  FUN_006050c0 ======
undefined4 * __cdecl FUN_006050c0(int param_1,char *param_2)

{
  void *this;
  undefined4 *puVar1;
  void *local_c;
  undefined1 *puStack_8;
  undefined4 local_4;
  
  local_4 = 0xffffffff;
  puStack_8 = &LAB_0087bcab;
  local_c = ExceptionList;
  ExceptionList = &local_c;
  this = (void *)FUN_00718cb0(0x4c);
  local_4 = 0;
  if (this != (void *)0x0) {
    puVar1 = FUN_0048e2b0(this,param_1,param_2);
    ExceptionList = local_c;
    return puVar1;
  }
  ExceptionList = local_c;
  return (undefined4 *)0x0;
}

// ====== 0x00605640  FUN_00605640 ======
undefined4 * __cdecl FUN_00605640(int param_1,char *param_2)

{
  void *this;
  undefined4 *puVar1;
  void *local_c;
  undefined1 *puStack_8;
  undefined4 local_4;
  
  local_4 = 0xffffffff;
  puStack_8 = &LAB_0087bccb;
  local_c = ExceptionList;
  ExceptionList = &local_c;
  this = (void *)FUN_00718cb0(0x58);
  local_4 = 0;
  if (this != (void *)0x0) {
    puVar1 = FUN_00478a50(this,param_1,param_2);
    ExceptionList = local_c;
    return puVar1;
  }
  ExceptionList = local_c;
  return (undefined4 *)0x0;
}

// ====== 0x00606120  FUN_00606120 ======
undefined4 * __fastcall FUN_00606120(undefined4 *param_1)

{
  FUN_006d5c00(param_1,0);
  *param_1 = &PTR_FUN_0088b26c;
  param_1[10] = 0;
  return param_1;
}

// ====== 0x00606a10  FUN_00606a10 ======
undefined4 * __cdecl FUN_00606a10(int param_1,char *param_2,char *param_3)

{
  void *this;
  undefined4 *puVar1;
  void *local_c;
  undefined1 *puStack_8;
  undefined4 local_4;
  
  local_4 = 0xffffffff;
  puStack_8 = &LAB_0087bceb;
  local_c = ExceptionList;
  ExceptionList = &local_c;
  this = (void *)FUN_00718cb0(0x88);
  local_4 = 0;
  if (this != (void *)0x0) {
    puVar1 = FUN_00475fb0(this,param_1,param_2,param_3);
    ExceptionList = local_c;
    return puVar1;
  }
  ExceptionList = local_c;
  return (undefined4 *)0x0;
}

// ====== 0x00607ec0  FUN_00607ec0 ======
undefined4 * FUN_00607ec0(undefined4 param_1,undefined4 *param_2)

{
  int iVar1;
  int local_4;
  
  iVar1 = FUN_0074e310(param_2,(byte *)s_Oi_PhysicsObjectClass_SetNetType_00940060);
  if (iVar1 == 0) {
    return (undefined4 *)0x0;
  }
  iVar1 = FUN_005bae00((int *)0x0,&local_4,DAT_00991520,1);
  if (iVar1 == -1) {
    return (undefined4 *)0x0;
  }
  *(undefined4 **)(local_4 + 0xec) = param_2;
  DAT_0095dd20 = DAT_0095dd20 + 1;
  return &DAT_0095dd20;
}

// ====== 0x0061e2a0  FUN_0061e2a0 ======
undefined4 * FUN_0061e2a0(void)

{
  undefined4 *puVar1;
  void *local_c;
  undefined1 *puStack_8;
  undefined4 local_4;
  
  local_4 = 0xffffffff;
  puStack_8 = &LAB_0087bd0b;
  local_c = ExceptionList;
  ExceptionList = &local_c;
  puVar1 = (undefined4 *)FUN_00718cb0(0x110);
  local_4 = 0;
  if (puVar1 != (undefined4 *)0x0) {
    puVar1 = FUN_004c6f10(puVar1);
    ExceptionList = local_c;
    return puVar1;
  }
  ExceptionList = local_c;
  return (undefined4 *)0x0;
}

// ====== 0x006200f0  FUN_006200f0 ======
undefined4 * FUN_006200f0(void)

{
  undefined4 *puVar1;
  void *local_c;
  undefined1 *puStack_8;
  undefined4 local_4;
  
  local_4 = 0xffffffff;
  puStack_8 = &LAB_0087bd2b;
  local_c = ExceptionList;
  ExceptionList = &local_c;
  puVar1 = (undefined4 *)FUN_00718cb0(0x124);
  local_4 = 0;
  if (puVar1 != (undefined4 *)0x0) {
    puVar1 = FUN_004cf210(puVar1);
    ExceptionList = local_c;
    return puVar1;
  }
  ExceptionList = local_c;
  return (undefined4 *)0x0;
}

// ====== 0x006204d0  FUN_006204d0 ======
int * __thiscall FUN_006204d0(void *this,int param_1)

{
  uint uVar1;
  void *this_00;
  int *piVar2;
  undefined4 uVar3;
  int iVar4;
  uint uVar5;
  uint uVar6;
  void *local_c;
  undefined1 *puStack_8;
  undefined4 local_4;
  
  local_4 = 0xffffffff;
  puStack_8 = &LAB_0087bd4b;
  local_c = ExceptionList;
  ExceptionList = &local_c;
  this_00 = (void *)FUN_00718cb0(8);
  local_4 = 0;
  if (this_00 == (void *)0x0) {
    piVar2 = (int *)0x0;
  }
  else {
    piVar2 = FUN_006205f0(this_00,param_1);
  }
  uVar1 = *(uint *)((int)this + 0x14);
  local_4 = 0xffffffff;
  if (*(uint *)((int)this + 0x10) <= uVar1) {
    uVar5 = *(int *)((int)this + 0x1c) + uVar1;
    if (uVar5 != *(uint *)((int)this + 0x10)) {
      uVar6 = uVar5;
      if (uVar5 < uVar1) {
        do {
          if (*(int *)(*(int *)((int)this + 0xc) + uVar6 * 4) != 0) {
            *(undefined4 *)(*(int *)((int)this + 0xc) + uVar6 * 4) = 0;
            *(int *)((int)this + 0x18) = *(int *)((int)this + 0x18) + -1;
          }
          uVar6 = uVar6 + 1;
        } while (uVar6 < *(uint *)((int)this + 0x14));
        *(uint *)((int)this + 0x14) = uVar5;
      }
      iVar4 = *(int *)((int)this + 0xc);
      *(uint *)((int)this + 0x10) = uVar5;
      uVar3 = FUN_00718cb0(uVar5 * 4);
      *(undefined4 *)((int)this + 0xc) = uVar3;
      uVar5 = 0;
      if (*(int *)((int)this + 0x14) != 0) {
        do {
          *(undefined4 *)(*(int *)((int)this + 0xc) + uVar5 * 4) =
               *(undefined4 *)(iVar4 + uVar5 * 4);
          uVar5 = uVar5 + 1;
        } while (uVar5 < *(uint *)((int)this + 0x14));
      }
      FUN_00718cf0(iVar4);
    }
    if (*(uint *)((int)this + 0x10) <= uVar1) {
      ExceptionList = local_c;
      return piVar2;
    }
  }
  if (uVar1 < *(uint *)((int)this + 0x14)) {
    if (piVar2 == (int *)0x0) {
      if (*(int *)(*(int *)((int)this + 0xc) + uVar1 * 4) == 0) goto LAB_006205d4;
      iVar4 = *(int *)((int)this + 0x18) + -1;
    }
    else {
      if (*(int *)(*(int *)((int)this + 0xc) + uVar1 * 4) != 0) goto LAB_006205d4;
      iVar4 = *(int *)((int)this + 0x18) + 1;
    }
  }
  else {
    *(uint *)((int)this + 0x14) = uVar1 + 1;
    if (piVar2 == (int *)0x0) goto LAB_006205d4;
    iVar4 = *(int *)((int)this + 0x18) + 1;
  }
  *(int *)((int)this + 0x18) = iVar4;
LAB_006205d4:
  *(int **)(*(int *)((int)this + 0xc) + uVar1 * 4) = piVar2;
  ExceptionList = local_c;
  return piVar2;
}

// ====== 0x006205f0  FUN_006205f0 ======
int * __thiscall FUN_006205f0(void *this,int param_1)

{
  int iVar1;
  int iVar2;
  void *local_c;
  undefined1 *puStack_8;
  undefined4 local_4;
  
  local_4 = 0xffffffff;
  puStack_8 = &LAB_0087bd6b;
  local_c = ExceptionList;
  ExceptionList = &local_c;
  *(int *)this = param_1;
  iVar1 = FUN_00718cb0(param_1 << 4);
  local_4 = 0;
  if (iVar1 == 0) {
    *(undefined4 *)((int)this + 4) = 0;
  }
  else {
    iVar2 = iVar1;
    if (-1 < param_1 + -1) {
      do {
        FUN_00401dc0(iVar2,8,2,&LAB_00620680);
        param_1 = param_1 + -1;
        iVar2 = iVar2 + 0x10;
      } while (param_1 != 0);
    }
    *(int *)((int)this + 4) = iVar1;
  }
  ExceptionList = local_c;
  return (int *)this;
}

// ====== 0x00622300  FUN_00622300 ======
undefined4 * __fastcall FUN_00622300(undefined4 *param_1)

{
  undefined4 uVar1;
  void *local_c;
  undefined1 *puStack_8;
  undefined4 local_4;
  
  local_4 = 0xffffffff;
  puStack_8 = &LAB_0087bda8;
  local_c = ExceptionList;
  ExceptionList = &local_c;
  FUN_0050e920(param_1,4,0x3f0ccccd,0x3f266666);
  local_4 = 0;
  param_1[0x14] = &PTR_FUN_0088ef44;
  param_1[0x16] = 1;
  param_1[0x19] = 1;
  param_1[0x17] = 0;
  param_1[0x18] = 0;
  uVar1 = FUN_00718cb0(4);
  param_1[0x15] = uVar1;
  param_1[0x1a] = 0;
  *param_1 = &PTR_FUN_0088ec9c;
  ExceptionList = local_c;
  return param_1;
}

// ====== 0x00620740  FUN_00620740 ======
undefined4 * __thiscall FUN_00620740(void *this,char *param_1)

{
  undefined4 uVar1;
  undefined4 *puVar2;
  char cVar3;
  void *this_00;
  int iVar4;
  undefined4 *puVar5;
  void *unaff_ESI;
  void *pvStack_c;
  undefined1 *puStack_8;
  undefined4 local_4;
  
  local_4 = 0xffffffff;
  puStack_8 = &LAB_0087bd8b;
  pvStack_c = ExceptionList;
  ExceptionList = &pvStack_c;
  this_00 = (void *)FUN_00718cb0(0x20);
  puVar5 = (undefined4 *)0x0;
  local_4 = 0;
  if (this_00 != (void *)0x0) {
    puVar5 = FUN_004f3da0(this_00,param_1);
  }
  uVar1 = *puVar5;
                    /* WARNING: Load size is inaccurate */
  local_4 = 0xffffffff;
  iVar4 = (**(code **)(*this + 4))(uVar1);
  puVar2 = *(undefined4 **)(*(int *)((int)this + 0xc) + iVar4 * 4);
  while( true ) {
    if (puVar2 == (undefined4 *)0x0) {
      iVar4 = FUN_00718cb0(0xc);
                    /* WARNING: Load size is inaccurate */
      (**(code **)(*this + 0xc))(iVar4,uVar1,puVar5);
      *(undefined4 *)(iVar4 + 8) = *(undefined4 *)(*(int *)((int)this + 0xc) + (int)pvStack_c * 4);
      *(int *)(*(int *)((int)this + 0xc) + (int)pvStack_c * 4) = iVar4;
      *(int *)((int)this + 4) = *(int *)((int)this + 4) + 1;
      ExceptionList = unaff_ESI;
      return puVar5;
    }
                    /* WARNING: Load size is inaccurate */
    cVar3 = (**(code **)(*this + 8))(uVar1,*puVar2);
    if (cVar3 != '\0') break;
    puVar2 = (undefined4 *)puVar2[2];
  }
                    /* WARNING: Load size is inaccurate */
  (**(code **)(*this + 0x10))(puVar2);
                    /* WARNING: Load size is inaccurate */
  (**(code **)(*this + 0xc))(puVar2,uVar1,puVar5);
  ExceptionList = unaff_ESI;
  return puVar5;
}

// ====== 0x0062bc20  FUN_0062bc20 ======
void __thiscall FUN_0062bc20(void *this,undefined1 *param_1)

{
  undefined1 local_1c [16];
  void *local_c;
  undefined1 *puStack_8;
  undefined4 local_4;
  
  local_4 = 0xffffffff;
  puStack_8 = &LAB_0087bde8;
  local_c = ExceptionList;
  ExceptionList = &local_c;
  FUN_006f3e90(local_1c,&lpWindowName_0097dc28);
  local_4 = 0;
  if (param_1 == (undefined1 *)0x0) {
    param_1 = local_1c;
  }
  FUN_006f4ee0((void *)((int)this + 0x114),param_1);
  FUN_006f54a0((void *)((int)this + 0x114),*(uint *)((int)this + 0x11c),' ');
  local_4 = 0xffffffff;
  FUN_006f3ef0((int)local_1c);
  ExceptionList = local_c;
  return;
}

// ====== 0x0062bca0  FUN_0062bca0 ======
undefined4 * __cdecl FUN_0062bca0(undefined4 param_1,undefined4 *param_2)

{
  int iVar1;
  char *pcVar2;
  int local_8;
  void *local_4;
  
  iVar1 = FUN_0074e310(param_2,(byte *)s_OiOO_STToggle_SetStateValue_00948428);
  if ((iVar1 != 0) && (iVar1 = FUN_005bae00((int *)0x0,(int *)&local_4,DAT_009912c8,1), iVar1 != -1)
     ) {
    if (puRam00000004 == &DAT_0095e960) {
      pcVar2 = (char *)FUN_007507d0(0);
      iVar1 = FUN_005bae00((int *)0x0,(int *)&param_2,DAT_0099148c,1);
      if (iVar1 != -1) {
        FUN_0054a080(local_4,local_8,pcVar2,(int)param_2);
        DAT_0095dd20 = DAT_0095dd20 + 1;
        return &DAT_0095dd20;
      }
    }
    else {
      FUN_00753260(DAT_009b3f7c,(byte *)s_Expected_None_or_string___s_foun_00930bdc);
    }
  }
  return (undefined4 *)0x0;
}

// ====== 0x0062cab0  FUN_0062cab0 ======
void __thiscall FUN_0062cab0(void *this,int param_1,int param_2,int param_3,int param_4)

{
  void *local_c;
  undefined1 *puStack_8;
  undefined4 local_4;
  
  puStack_8 = &LAB_0087be08;
  local_c = ExceptionList;
  local_4 = 0;
  ExceptionList = &local_c;
  FUN_00522790(this,param_1,param_2,param_3,param_4);
  ExceptionList = local_c;
  return;
}

// ====== 0x0062cbd0  FUN_0062cbd0 ======
void __thiscall FUN_0062cbd0(void *this,int param_1,int param_2,int param_3,int param_4)

{
  void *local_c;
  undefined1 *puStack_8;
  undefined4 local_4;
  
  puStack_8 = &LAB_0087be28;
  local_c = ExceptionList;
  local_4 = 0;
  ExceptionList = &local_c;
  FUN_005227d0(this,param_1,param_2,param_3,param_4);
  ExceptionList = local_c;
  return;
}

// ====== 0x0062ccf0  FUN_0062ccf0 ======
void __thiscall
FUN_0062ccf0(void *this,undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4)

{
  void *local_c;
  undefined1 *puStack_8;
  undefined4 local_4;
  
  puStack_8 = &LAB_0087be48;
  local_c = ExceptionList;
  local_4 = 0;
  ExceptionList = &local_c;
  FUN_00522810(this,param_1,param_2,param_3,param_4);
  ExceptionList = local_c;
  return;
}

// ====== 0x00637350  FUN_00637350 ======
undefined4 * __cdecl FUN_00637350(char *param_1,char *param_2,int param_3)

{
  void *this;
  undefined4 *puVar1;
  void *local_c;
  undefined1 *puStack_8;
  undefined4 local_4;
  
  local_4 = 0xffffffff;
  puStack_8 = &LAB_0087be6b;
  local_c = ExceptionList;
  ExceptionList = &local_c;
  this = (void *)FUN_00718cb0(0x30);
  local_4 = 0;
  if (this != (void *)0x0) {
    puVar1 = FUN_0055d440(this,DAT_009a09d4,*(undefined4 *)(*(int *)(DAT_009a09d0 + 0x10) + 4),
                          param_1,param_2,param_3);
    ExceptionList = local_c;
    return puVar1;
  }
  ExceptionList = local_c;
  return (undefined4 *)0x0;
}

// ====== 0x006390a0  FUN_006390a0 ======
undefined4 * __thiscall FUN_006390a0(void *this,undefined4 *param_1)

{
  undefined4 *puVar1;
  float in_stack_00000014;
  float in_stack_00000018;
  float in_stack_0000001c;
  float in_stack_ffffffc8;
  float in_stack_ffffffcc;
  float in_stack_ffffffd0;
  float local_18 [3];
  void *local_c;
  undefined1 *puStack_8;
  undefined4 local_4;
  
  puStack_8 = &LAB_0087be90;
  local_c = ExceptionList;
  local_4 = 1;
  ExceptionList = &local_c;
  FUN_00423480(&stack0xffffffc8,(undefined4 *)&stack0x00000008);
  puVar1 = (undefined4 *)
           FUN_00499590(this,local_18,in_stack_ffffffc8,in_stack_ffffffcc,in_stack_ffffffd0,
                        in_stack_00000014,in_stack_00000018,in_stack_0000001c);
  *param_1 = *puVar1;
  param_1[1] = puVar1[1];
  param_1[2] = puVar1[2];
  ExceptionList = local_c;
  return param_1;
}

// ====== 0x00639fd0  FUN_00639fd0 ======
void __thiscall FUN_00639fd0(void *this)

{
  undefined4 in_stack_0000001c;
  undefined4 in_stack_00000020;
  undefined4 in_stack_00000024;
  undefined4 in_stack_ffffffc8;
  undefined4 uVar1;
  undefined4 *puVar2;
  undefined4 in_stack_ffffffd4;
  undefined4 in_stack_ffffffd8;
  undefined4 in_stack_ffffffdc;
  void *local_c;
  undefined1 *puStack_8;
  undefined4 local_4;
  
  puStack_8 = &LAB_0087beb8;
  local_c = ExceptionList;
  local_4 = 2;
  puVar2 = (undefined4 *)&stack0x00000010;
  uVar1 = 0x63a021;
  ExceptionList = &local_c;
  FUN_00423480(&stack0xffffffd4,puVar2);
  FUN_00423480(&stack0xffffffc8,(undefined4 *)&stack0x00000004);
  FUN_0063a050(this,in_stack_ffffffc8,uVar1,puVar2,in_stack_ffffffd4,in_stack_ffffffd8,
               in_stack_ffffffdc,in_stack_0000001c,in_stack_00000020,in_stack_00000024);
  ExceptionList = local_c;
  return;
}

// ====== 0x0063a160  FUN_0063a160 ======
void __thiscall FUN_0063a160(void *this,undefined4 param_1,undefined4 param_2,undefined4 param_3)

{
  *(undefined4 *)((int)this + 0x44) = param_1;
  *(undefined4 *)((int)this + 0x48) = param_2;
  *(undefined4 *)((int)this + 0x4c) = param_3;
  return;
}

// ====== 0x0063a050  FUN_0063a050 ======
void __thiscall
FUN_0063a050(void *this,undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4,
            undefined4 param_5,undefined4 param_6,undefined4 param_7,undefined4 param_8,
            undefined4 param_9)

{
  *(undefined4 *)((int)this + 0x20) = param_1;
  *(undefined4 *)((int)this + 0x24) = param_2;
  *(undefined4 *)((int)this + 0x28) = param_3;
  *(undefined4 *)((int)this + 0x2c) = param_4;
  *(undefined4 *)((int)this + 0x30) = param_5;
  *(undefined4 *)((int)this + 0x34) = param_6;
  *(undefined4 *)((int)this + 0x38) = param_7;
  *(undefined4 *)((int)this + 0x3c) = param_8;
  *(undefined4 *)((int)this + 0x40) = param_9;
  return;
}

// ====== 0x0063a210  FUN_0063a210 ======
void __thiscall FUN_0063a210(void *this,undefined4 *param_1)

{
  *param_1 = *(undefined4 *)((int)this + 0x20);
  param_1[1] = *(undefined4 *)((int)this + 0x24);
  param_1[2] = *(undefined4 *)((int)this + 0x28);
  return;
}

// ====== 0x0063a2d0  FUN_0063a2d0 ======
void __thiscall FUN_0063a2d0(void *this,undefined4 *param_1)

{
  *param_1 = *(undefined4 *)((int)this + 0x2c);
  param_1[1] = *(undefined4 *)((int)this + 0x30);
  param_1[2] = *(undefined4 *)((int)this + 0x34);
  return;
}

// ====== 0x0063a390  FUN_0063a390 ======
void __thiscall FUN_0063a390(void *this,undefined4 *param_1)

{
  *param_1 = *(undefined4 *)((int)this + 0x38);
  param_1[1] = *(undefined4 *)((int)this + 0x3c);
  param_1[2] = *(undefined4 *)((int)this + 0x40);
  return;
}

// ====== 0x0063d620  FUN_0063d620 ======
void __thiscall
FUN_0063d620(void *this,undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4)

{
  *(undefined4 *)((int)this + 0xd4) = param_1;
  *(undefined4 *)((int)this + 0xd8) = param_2;
  *(undefined4 *)((int)this + 0xdc) = param_3;
  *(undefined4 *)((int)this + 0xe0) = param_4;
  return;
}

// ====== 0x0063d710  FUN_0063d710 ======
void __thiscall
FUN_0063d710(void *this,undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4)

{
  *(undefined4 *)((int)this + 0xe4) = param_1;
  *(undefined4 *)((int)this + 0xe8) = param_2;
  *(undefined4 *)((int)this + 0xec) = param_3;
  *(undefined4 *)((int)this + 0xf0) = param_4;
  return;
}

// ====== 0x0063d800  FUN_0063d800 ======
void __thiscall
FUN_0063d800(void *this,undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4)

{
  *(undefined4 *)((int)this + 0xf4) = param_1;
  *(undefined4 *)((int)this + 0xf8) = param_2;
  *(undefined4 *)((int)this + 0xfc) = param_3;
  *(undefined4 *)((int)this + 0x100) = param_4;
  return;
}

// ====== 0x0063d8f0  FUN_0063d8f0 ======
void __thiscall
FUN_0063d8f0(void *this,undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4)

{
  *(undefined4 *)((int)this + 0x104) = param_1;
  *(undefined4 *)((int)this + 0x108) = param_2;
  *(undefined4 *)((int)this + 0x10c) = param_3;
  *(undefined4 *)((int)this + 0x110) = param_4;
  return;
}
