// 19_exception_unwind.c - Decompiled from stbc.exe
// Generated by decompile_all.py


// ====== 0x008700e8  FUN_008700e8 ======
uint __cdecl FUN_008700e8(uint param_1)

{
  byte bVar1;
  uint uVar2;
  DWORD *pDVar3;
  HANDLE hTargetProcessHandle;
  HANDLE hSourceHandle;
  HANDLE hSourceProcessHandle;
  int iVar4;
  HANDLE *lpTargetHandle;
  DWORD DVar5;
  BOOL BVar6;
  DWORD dwOptions;
  HANDLE local_8;
  
  if (param_1 < uNumber_009b4100) {
    iVar4 = (param_1 & 0x1f) * 0x24;
    if ((*(byte *)((&DAT_009b4000)[(int)param_1 >> 5] + 4 + iVar4) & 1) != 0) {
      FUN_008680cf(param_1);
      bVar1 = *(byte *)((&DAT_009b4000)[(int)param_1 >> 5] + 4 + iVar4);
      uVar2 = FUN_00867dc8();
      if (uVar2 == 0xffffffff) {
        pDVar3 = FUN_0085cbd7();
        *pDVar3 = 0x18;
        pDVar3 = FUN_0085cbe0();
        *pDVar3 = 0;
        FUN_0086812e(param_1);
        return 0xffffffff;
      }
      dwOptions = 2;
      BVar6 = 1;
      lpTargetHandle = &local_8;
      DVar5 = 0;
      hTargetProcessHandle = GetCurrentProcess();
      hSourceHandle = (HANDLE)FUN_00867fe6(param_1);
      hSourceProcessHandle = GetCurrentProcess();
      BVar6 = DuplicateHandle(hSourceProcessHandle,hSourceHandle,hTargetProcessHandle,lpTargetHandle
                              ,DVar5,BVar6,dwOptions);
      if (BVar6 == 0) {
        DVar5 = GetLastError();
      }
      else {
        FUN_00867eeb(uVar2,local_8);
        DVar5 = 0;
      }
      FUN_0086812e(uVar2);
      FUN_0086812e(param_1);
      if (DVar5 != 0) {
        FUN_0085cb64(DVar5);
        return 0xffffffff;
      }
      *(byte *)((&DAT_009b4000)[(int)uVar2 >> 5] + 4 + (uVar2 & 0x1f) * 0x24) = bVar1 & 0xef;
      return uVar2;
    }
  }
  pDVar3 = FUN_0085cbd7();
  *pDVar3 = 9;
  pDVar3 = FUN_0085cbe0();
  *pDVar3 = 0;
  return 0xffffffff;
}

// ====== 0x008701f0  FUN_008701f0 ======
undefined4 __thiscall FUN_008701f0(void *this,uint param_1,uint param_2)

{
  int iVar1;
  DWORD *pDVar2;
  HANDLE hTargetProcessHandle;
  HANDLE hSourceHandle;
  HANDLE hSourceProcessHandle;
  uint uVar3;
  int iVar4;
  undefined4 uVar5;
  void **lpTargetHandle;
  DWORD dwDesiredAccess;
  BOOL BVar6;
  DWORD dwOptions;
  void *local_8;
  
  local_8 = this;
  if (uNumber_009b4100 <= param_1) goto LAB_00870291;
  iVar4 = (param_1 & 0x1f) * 0x24;
  if (((*(byte *)((&DAT_009b4000)[(int)param_1 >> 5] + 4 + iVar4) & 1) == 0) || (0x7ff < param_2))
  goto LAB_00870291;
  if (((int)uNumber_009b4100 <= (int)param_2) && (iVar1 = FUN_00870361(param_2), iVar1 != 0)) {
    pDVar2 = FUN_0085cbd7();
    *pDVar2 = 0xc;
    return 0xffffffff;
  }
  if ((int)param_1 < (int)param_2) {
    FUN_008680cf(param_1);
    uVar3 = param_2;
LAB_00870271:
    FUN_008680cf(uVar3);
  }
  else if ((int)param_2 < (int)param_1) {
    FUN_008680cf(param_2);
    uVar3 = param_1;
    goto LAB_00870271;
  }
  if ((*(byte *)((&DAT_009b4000)[(int)param_1 >> 5] + 4 + iVar4) & 1) != 0) {
    if (param_1 == param_2) {
      uVar5 = 0;
    }
    else {
      iVar1 = (param_2 & 0x1f) * 0x24;
      if ((*(byte *)((&DAT_009b4000)[(int)param_2 >> 5] + 4 + iVar1) & 1) != 0) {
        FUN_0086398d(param_2);
      }
      dwOptions = 2;
      BVar6 = 1;
      lpTargetHandle = &local_8;
      dwDesiredAccess = 0;
      hTargetProcessHandle = GetCurrentProcess();
      hSourceHandle = (HANDLE)FUN_00867fe6(param_1);
      hSourceProcessHandle = GetCurrentProcess();
      BVar6 = DuplicateHandle(hSourceProcessHandle,hSourceHandle,hTargetProcessHandle,lpTargetHandle
                              ,dwDesiredAccess,BVar6,dwOptions);
      if (BVar6 == 0) {
        uVar3 = GetLastError();
      }
      else {
        FUN_00867eeb(param_2,local_8);
        uVar3 = 0;
      }
      if (uVar3 == 0) {
        uVar5 = 0;
        *(byte *)((&DAT_009b4000)[(int)param_2 >> 5] + 4 + iVar1) =
             *(byte *)((&DAT_009b4000)[(int)param_1 >> 5] + 4 + iVar4) & 0xef;
      }
      else {
        FUN_0085cb64(uVar3);
        uVar5 = 0xffffffff;
      }
    }
    FUN_0086812e(param_1);
    FUN_0086812e(param_2);
    return uVar5;
  }
  FUN_0086812e(param_1);
  FUN_0086812e(param_2);
LAB_00870291:
  pDVar2 = FUN_0085cbd7();
  *pDVar2 = 9;
  pDVar2 = FUN_0085cbe0();
  *pDVar2 = 0;
  return 0xffffffff;
}

// ====== 0x00870361  FUN_00870361 ======
undefined4 __cdecl FUN_00870361(int param_1)

{
  undefined4 *puVar1;
  undefined4 *puVar2;
  int *piVar3;
  
  if ((int)uNumber_009b4100 <= param_1) {
    piVar3 = &DAT_009b4000;
    do {
      if (*piVar3 == 0) {
        puVar2 = (undefined4 *)_malloc(0x480);
        if (puVar2 == (undefined4 *)0x0) {
          return 0xffffffff;
        }
        uNumber_009b4100 = uNumber_009b4100 + 0x20;
        *piVar3 = (int)puVar2;
        puVar1 = puVar2;
        for (; puVar2 < puVar1 + 0x120; puVar2 = puVar2 + 9) {
          *(undefined1 *)(puVar2 + 1) = 0;
          *puVar2 = 0xffffffff;
          puVar2[2] = 0;
          *(undefined1 *)((int)puVar2 + 5) = 10;
          puVar1 = (undefined4 *)*piVar3;
        }
      }
      piVar3 = piVar3 + 1;
    } while ((int)uNumber_009b4100 <= param_1);
  }
  return 0;
}

// ====== 0x008703cb  FUN_008703cb ======
undefined4 __cdecl FUN_008703cb(uint param_1,uint *param_2)

{
  int *piVar1;
  uint *puVar2;
  DWORD DVar3;
  DWORD *pDVar4;
  BOOL BVar5;
  uint uVar6;
  int iVar7;
  _BY_HANDLE_FILE_INFORMATION local_54;
  _SYSTEMTIME local_20;
  _FILETIME local_10;
  undefined4 local_8;
  
  local_8 = 0;
  if (uNumber_009b4100 <= param_1) {
LAB_0087064c:
    pDVar4 = FUN_0085cbd7();
    *pDVar4 = 9;
    return 0xffffffff;
  }
  piVar1 = &DAT_009b4000 + ((int)param_1 >> 5);
  iVar7 = (param_1 & 0x1f) * 0x24;
  if ((*(byte *)(*piVar1 + 4 + iVar7) & 1) == 0) goto LAB_0087064c;
  FUN_008680cf(param_1);
  DVar3 = GetFileType(*(HANDLE *)(*piVar1 + iVar7));
  puVar2 = param_2;
  uVar6 = DVar3 & 0xffff7fff;
  if (uVar6 != 1) {
    if (uVar6 == 2) {
      *(undefined2 *)((int)param_2 + 6) = 0x2000;
    }
    else {
      if (uVar6 != 3) {
        if (uVar6 == 0) {
          pDVar4 = FUN_0085cbd7();
          *pDVar4 = 9;
          goto LAB_00870446;
        }
        goto LAB_008704f2;
      }
      *(undefined2 *)((int)param_2 + 6) = 0x1000;
    }
    *(undefined2 *)(param_2 + 2) = 1;
    *param_2 = param_1;
    param_2[4] = param_1;
    *(undefined2 *)(param_2 + 1) = 0;
    *(undefined2 *)(param_2 + 3) = 0;
    *(undefined2 *)((int)param_2 + 10) = 0;
    param_2[8] = 0;
    param_2[7] = 0;
    param_2[6] = 0;
    if (uVar6 == 2) {
      param_2[5] = 0;
    }
    else {
      BVar5 = PeekNamedPipe(*(HANDLE *)(*piVar1 + iVar7),(LPVOID)0x0,0,(LPDWORD)0x0,
                            (LPDWORD)&param_2,(LPDWORD)0x0);
      if (BVar5 == 0) {
        puVar2[5] = 0;
      }
      else {
        puVar2[5] = (uint)param_2;
      }
    }
    goto LAB_0087044a;
  }
  *(undefined2 *)((int)param_2 + 6) = 0;
  *(undefined2 *)(param_2 + 3) = 0;
  *(undefined2 *)((int)param_2 + 10) = 0;
  *(undefined2 *)(param_2 + 1) = 0;
  *(undefined2 *)(param_2 + 2) = 1;
  BVar5 = GetFileInformationByHandle(*(HANDLE *)(*piVar1 + iVar7),&local_54);
  if (BVar5 == 0) {
LAB_008704f2:
    DVar3 = GetLastError();
    FUN_0085cb64(DVar3);
  }
  else {
    if (((byte)local_54.dwFileAttributes & 1) == 0) {
      *(ushort *)((int)puVar2 + 6) = *(ushort *)((int)puVar2 + 6) | 0x1b6;
    }
    else {
      *(ushort *)((int)puVar2 + 6) = *(ushort *)((int)puVar2 + 6) | 0x124;
    }
    BVar5 = FileTimeToLocalFileTime(&local_54.ftLastWriteTime,&local_10);
    if ((BVar5 != 0) && (BVar5 = FileTimeToSystemTime(&local_10,&local_20), BVar5 != 0)) {
      uVar6 = FUN_008679d8((uint)local_20.wYear,(uint)local_20.wMonth,(uint)local_20.wDay,
                           (uint)local_20.wHour,(uint)local_20.wMinute,(uint)local_20.wSecond,-1);
      puVar2[7] = uVar6;
      if ((local_54.ftLastAccessTime.dwLowDateTime == 0) &&
         (local_54.ftLastAccessTime.dwHighDateTime == 0)) {
LAB_008705d0:
        puVar2[6] = uVar6;
        if ((local_54.ftCreationTime.dwLowDateTime == 0) &&
           (local_54.ftCreationTime.dwHighDateTime == 0)) {
          uVar6 = puVar2[7];
        }
        else {
          BVar5 = FileTimeToLocalFileTime(&local_54.ftCreationTime,&local_10);
          if ((BVar5 == 0) || (BVar5 = FileTimeToSystemTime(&local_10,&local_20), BVar5 == 0))
          goto LAB_00870644;
          uVar6 = FUN_008679d8((uint)local_20.wYear,(uint)local_20.wMonth,(uint)local_20.wDay,
                               (uint)local_20.wHour,(uint)local_20.wMinute,(uint)local_20.wSecond,-1
                              );
        }
        *(byte *)((int)puVar2 + 7) = *(byte *)((int)puVar2 + 7) | 0x80;
        puVar2[8] = uVar6;
        *puVar2 = 0;
        puVar2[5] = local_54.nFileSizeLow;
        puVar2[4] = 0;
      }
      else {
        BVar5 = FileTimeToLocalFileTime(&local_54.ftLastAccessTime,&local_10);
        if ((BVar5 != 0) && (BVar5 = FileTimeToSystemTime(&local_10,&local_20), BVar5 != 0)) {
          uVar6 = FUN_008679d8((uint)local_20.wYear,(uint)local_20.wMonth,(uint)local_20.wDay,
                               (uint)local_20.wHour,(uint)local_20.wMinute,(uint)local_20.wSecond,-1
                              );
          goto LAB_008705d0;
        }
LAB_00870644:
        local_8 = 0xffffffff;
      }
      goto LAB_0087044a;
    }
  }
LAB_00870446:
  local_8 = 0xffffffff;
LAB_0087044a:
  FUN_0086812e(param_1);
  return local_8;
}

// ====== 0x0087065e  FUN_0087065e ======
/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

undefined4 * __cdecl FUN_0087065e(uint param_1,char *param_2)

{
  char cVar1;
  bool bVar2;
  bool bVar3;
  bool bVar4;
  bool bVar5;
  bool bVar6;
  undefined4 *puVar7;
  
  if (((uNumber_009b4100 <= param_1) ||
      (bVar3 = true,
      (*(byte *)((&DAT_009b4000)[(int)param_1 >> 5] + 4 + (param_1 & 0x1f) * 0x24) & 1) == 0)) ||
     (puVar7 = FUN_00863bab(), puVar7 == (undefined4 *)0x0)) {
    return (undefined4 *)0x0;
  }
  cVar1 = *param_2;
  if (cVar1 != 'a') {
    if (cVar1 == 'r') {
      puVar7[3] = 1;
      goto LAB_008706c4;
    }
    if (cVar1 != 'w') {
      puVar7 = (undefined4 *)0x0;
      goto LAB_00870740;
    }
  }
  puVar7[3] = 2;
LAB_008706c4:
  puVar7[3] = puVar7[3] | DAT_009b3cd8;
  bVar2 = bVar3;
  bVar4 = false;
  bVar6 = false;
LAB_008706d4:
  bVar5 = bVar6;
  cVar1 = param_2[1];
  param_2 = param_2 + 1;
  if ((cVar1 == '\0') || (!bVar2)) goto LAB_00870733;
  bVar6 = bVar5;
  if (cVar1 == '+') {
    if ((puVar7[3] & 0x80) == 0) {
      puVar7[3] = puVar7[3] & 0xfffffffc | 0x80;
      goto LAB_008706d4;
    }
  }
  else {
    if (cVar1 == 'b') {
LAB_00870714:
      bVar6 = bVar3;
      if (bVar5) goto LAB_00870726;
      goto LAB_008706d4;
    }
    if (cVar1 == 'c') {
      if (bVar4) goto LAB_00870726;
      *(byte *)((int)puVar7 + 0xd) = *(byte *)((int)puVar7 + 0xd) | 0x40;
      bVar4 = bVar3;
      goto LAB_008706d4;
    }
    if (cVar1 == 'n') {
      if (bVar4) goto LAB_00870726;
      *(byte *)((int)puVar7 + 0xd) = *(byte *)((int)puVar7 + 0xd) & 0xbf;
      bVar4 = bVar3;
      goto LAB_008706d4;
    }
    if (cVar1 == 't') goto LAB_00870714;
  }
LAB_00870726:
  bVar2 = false;
  bVar6 = bVar5;
  goto LAB_008706d4;
LAB_00870733:
  _DAT_009b3968 = _DAT_009b3968 + 1;
  puVar7[4] = param_1;
LAB_00870740:
  FUN_0085bfc5((uint)puVar7);
  return puVar7;
}

// ====== 0x00870751  GetCurrentProcessId ======
DWORD GetCurrentProcessId(void)

{
  DWORD DVar1;
  
                    /* WARNING: Could not recover jumptable at 0x00870751. Too many branches */
                    /* WARNING: Treating indirect jump as call */
  DVar1 = GetCurrentProcessId();
  return DVar1;
}

// ====== 0x00870757  FUN_00870757 ======
void __cdecl FUN_00870757(byte *param_1,byte *param_2,byte *param_3,byte *param_4,byte *param_5)

{
  byte bVar1;
  byte *pbVar2;
  byte *pbVar3;
  
  if ((param_2 != (byte *)0x0) && (*param_2 != 0)) {
    *param_1 = *param_2;
    param_1[1] = 0x3a;
    param_1 = param_1 + 2;
  }
  if ((param_3 != (byte *)0x0) && (bVar1 = *param_3, pbVar2 = param_3, bVar1 != 0)) {
    do {
      pbVar3 = param_1;
      *pbVar3 = bVar1;
      bVar1 = pbVar2[1];
      param_1 = pbVar3 + 1;
      pbVar2 = pbVar2 + 1;
    } while (bVar1 != 0);
    pbVar2 = FUN_00870cd7(param_3,pbVar2);
    if ((*pbVar2 != 0x2f) && (*pbVar2 != 0x5c)) {
      *param_1 = 0x5c;
      param_1 = pbVar3 + 2;
    }
  }
  if (param_4 != (byte *)0x0) {
    bVar1 = *param_4;
    while (bVar1 != 0) {
      *param_1 = bVar1;
      pbVar2 = param_4 + 1;
      param_1 = param_1 + 1;
      param_4 = param_4 + 1;
      bVar1 = *pbVar2;
    }
  }
  if (param_5 == (byte *)0x0) {
    *param_1 = 0;
  }
  else {
    if ((*param_5 != 0) && (*param_5 != 0x2e)) {
      *param_1 = 0x2e;
      param_1 = param_1 + 1;
    }
    do {
      bVar1 = *param_5;
      *param_1 = bVar1;
      param_1 = param_1 + 1;
      param_5 = param_5 + 1;
    } while (bVar1 != 0);
  }
  return;
}

// ====== 0x008707e8  FUN_008707e8 ======
uint __cdecl FUN_008707e8(uint param_1)

{
  uint uVar1;
  undefined2 extraout_var;
  LONG LVar2;
  undefined2 uVar3;
  ushort uVar4;
  bool bVar5;
  
  uVar1 = 0xffff;
  uVar4 = (ushort)param_1;
  if (uVar4 != 0xffff) {
    if (DAT_009b3a68 == 0) {
      if ((0x40 < uVar4) && (uVar4 < 0x5b)) {
        param_1 = param_1 + 0x20;
      }
      uVar1 = param_1 & 0xffff;
    }
    else {
      InterlockedIncrement(&DAT_009b4334);
      bVar5 = DAT_009b4330 != 0;
      if (bVar5) {
        InterlockedDecrement(&DAT_009b4334);
        FUN_00860a61(0x13);
      }
      uVar1 = FUN_00870862(param_1);
      if (bVar5) {
        FUN_00860ac2(0x13);
        uVar3 = extraout_var;
      }
      else {
        LVar2 = InterlockedDecrement(&DAT_009b4334);
        uVar3 = (short)((uint)LVar2 >> 0x10);
      }
      uVar1 = CONCAT22(uVar3,(short)uVar1);
    }
  }
  return uVar1;
}

// ====== 0x00870862  FUN_00870862 ======
uint __cdecl FUN_00870862(uint param_1)

{
  WCHAR WVar1;
  uint uVar2;
  size_t sVar3;
  undefined2 uVar4;
  WCHAR local_6;
  
  WVar1 = (WCHAR)param_1;
  if (WVar1 == L'\xffff') {
    return param_1;
  }
  if (DAT_009b3a68 == 0) {
    if ((0x40 < (ushort)WVar1) && ((ushort)WVar1 < 0x5b)) {
      return param_1 + 0x20;
    }
  }
  else {
    if ((ushort)WVar1 < 0x100) {
      uVar2 = FUN_00868be8(WVar1,1);
      if (uVar2 == 0) {
        return param_1 & 0xffff;
      }
    }
    sVar3 = FUN_00870d44(DAT_009b3a68,0x100,(LPCWSTR)&param_1,1,&local_6,1,0);
    uVar4 = (undefined2)(sVar3 >> 0x10);
    param_1 = CONCAT22(uVar4,(undefined2)param_1);
    if (sVar3 != 0) {
      param_1 = CONCAT22(uVar4,local_6);
    }
  }
  return param_1;
}

// ====== 0x008708d7  FUN_008708d7 ======
uint __thiscall FUN_008708d7(void *this,byte *param_1,byte *param_2)

{
  byte *pbVar1;
  byte bVar2;
  uint uVar3;
  int iVar4;
  byte *pbVar5;
  ushort uVar6;
  ushort uVar7;
  byte *local_10;
  byte *local_c;
  byte local_8;
  byte local_7;
  
  if (DAT_009b411c == 0) {
    uVar3 = FUN_0085b2b0(this,param_1,param_2);
  }
  else {
    FUN_00860a61(0x19);
    local_10 = param_2 + -1;
    local_c = param_1 + -1;
    do {
      uVar3 = (uint)*param_1;
      pbVar5 = param_1 + 1;
      pbVar1 = local_c + 1;
      if (((&DAT_009b4221)[uVar3] & 4) == 0) {
        param_1 = pbVar5;
        local_c = pbVar1;
        if (((&DAT_009b4221)[uVar3] & 0x10) == 0x10) {
          uVar3 = (uint)(byte)(&DAT_009b4120)[uVar3];
        }
      }
      else if (*pbVar5 == 0) {
        uVar3 = 0;
        param_1 = pbVar5;
        local_c = pbVar1;
      }
      else {
        iVar4 = FUN_00867640(DAT_009b4324,0x200,(char *)pbVar1,2,(LPWSTR)&local_8,2,
                             CodePage_009b4104,1);
        if (iVar4 == 1) {
          uVar3 = (uint)local_8;
        }
        else {
          if (iVar4 != 2) goto LAB_00870a3b;
          uVar3 = (uint)local_8 * 0x100 + (uint)local_7;
        }
        param_1 = param_1 + 2;
        local_c = local_c + 2;
      }
      bVar2 = *param_2;
      uVar6 = (ushort)bVar2;
      pbVar5 = param_2 + 1;
      pbVar1 = local_10 + 1;
      if (((&DAT_009b4221)[bVar2] & 4) == 0) {
        param_2 = pbVar5;
        local_10 = pbVar1;
        if (((&DAT_009b4221)[bVar2] & 0x10) == 0x10) {
          uVar6 = (ushort)(byte)(&DAT_009b4120)[bVar2];
        }
      }
      else if (*pbVar5 == 0) {
        uVar6 = 0;
        param_2 = pbVar5;
        local_10 = pbVar1;
      }
      else {
        iVar4 = FUN_00867640(DAT_009b4324,0x200,(char *)pbVar1,2,(LPWSTR)&local_8,2,
                             CodePage_009b4104,1);
        if (iVar4 == 1) {
          uVar6 = (ushort)local_8;
        }
        else {
          if (iVar4 != 2) {
LAB_00870a3b:
            FUN_00860ac2(0x19);
            return 0x7fffffff;
          }
          uVar6 = (ushort)local_8 * 0x100 + (ushort)local_7;
        }
        param_2 = param_2 + 2;
        local_10 = local_10 + 2;
      }
      uVar7 = (ushort)uVar3;
      if (uVar7 != uVar6) {
        FUN_00860ac2(0x19);
        return (-(uint)(uVar6 < uVar7) & 2) - 1;
      }
    } while (uVar7 != 0);
    FUN_00860ac2(0x19);
    uVar3 = 0;
  }
  return uVar3;
}

// ====== 0x00870a6c  FUN_00870a6c ======
uint * __cdecl FUN_00870a6c(uint *param_1,LPCSTR param_2,size_t param_3)

{
  LPCSTR lpFileName;
  uint *puVar1;
  DWORD *pDVar2;
  DWORD DVar3;
  
  lpFileName = param_2;
  if ((param_2 != (LPCSTR)0x0) && (*param_2 != '\0')) {
    puVar1 = param_1;
    if (param_1 == (uint *)0x0) {
      puVar1 = (uint *)_malloc(0x104);
      if (puVar1 == (uint *)0x0) {
        pDVar2 = FUN_0085cbd7();
        *pDVar2 = 0xc;
        return (uint *)0x0;
      }
      param_3 = 0x104;
    }
    DVar3 = GetFullPathNameA(lpFileName,param_3,(LPSTR)puVar1,&param_2);
    if (DVar3 < param_3) {
      if (DVar3 != 0) {
        return puVar1;
      }
      if (param_1 == (uint *)0x0) {
        FUN_0085adc4((undefined *)puVar1);
      }
      DVar3 = GetLastError();
      FUN_0085cb64(DVar3);
    }
    else {
      if (param_1 == (uint *)0x0) {
        FUN_0085adc4((undefined *)puVar1);
      }
      pDVar2 = FUN_0085cbd7();
      *pDVar2 = 0x22;
    }
    return (uint *)0x0;
  }
  puVar1 = FUN_00859eeb(param_1,param_3);
  return puVar1;
}

// ====== 0x00870b11  FUN_00870b11 ======
int FUN_00870b11(void)

{
  DWORD DVar1;
  uint uVar2;
  int iVar3;
  byte local_108;
  char local_107;
  
  iVar3 = 0;
  DVar1 = GetCurrentDirectoryA(0x104,(LPSTR)&local_108);
  if ((DVar1 != 0) && (local_107 == ':')) {
    uVar2 = FUN_0085e89f((uint)local_108);
    iVar3 = uVar2 - 0x40;
  }
  return iVar3;
}

// ====== 0x00870b54  FUN_00870b54 ======
undefined4 __cdecl FUN_00870b54(uint param_1)

{
  uint uVar1;
  uint uVar2;
  BOOL BVar3;
  DWORD DVar4;
  DWORD *pDVar5;
  undefined4 uVar6;
  
  uVar2 = param_1;
  if (((int)param_1 < 1) || (0x1f < (int)param_1)) {
    pDVar5 = FUN_0085cbd7();
    *pDVar5 = 0xd;
    pDVar5 = FUN_0085cbe0();
    *pDVar5 = 0xf;
    uVar6 = 0xffffffff;
  }
  else {
    FUN_00860a61(0xc);
    uVar1 = param_1 >> 0x10;
    param_1._0_2_ = CONCAT11(0x3a,(char)uVar2 + '@');
    param_1 = CONCAT22((short)uVar1,(undefined2)param_1) & 0xff00ffff;
    BVar3 = SetCurrentDirectoryA((LPCSTR)&param_1);
    if (BVar3 == 0) {
      DVar4 = GetLastError();
      FUN_0085cb64(DVar4);
      uVar6 = 0xffffffff;
    }
    else {
      uVar6 = 0;
    }
    FUN_00860ac2(0xc);
  }
  return uVar6;
}

// ====== 0x00870bc7  FUN_00870bc7 ======
uint __cdecl FUN_00870bc7(uint param_1)

{
  uint uVar1;
  uint uVar2;
  int iVar3;
  uint uVar4;
  undefined1 uVar5;
  undefined2 local_8;
  
  uVar4 = param_1;
  if (param_1 < 0x100) {
    if (((&DAT_009b4221)[param_1] & 0x10) == 0x10) {
      uVar4 = (uint)(byte)(&DAT_009b4120)[param_1];
    }
  }
  else {
    uVar5 = (undefined1)param_1;
    uVar2 = param_1 >> 8;
    uVar1 = param_1 >> 8;
    param_1 = CONCAT13(uVar5,CONCAT12((char)uVar1,(undefined2)param_1));
    if ((((&DAT_009b4221)[uVar2 & 0xff] & 4) != 0) &&
       (iVar3 = FUN_00867640(DAT_009b4324,0x100,(char *)((int)&param_1 + 2),2,&local_8,2,
                             CodePage_009b4104,1), iVar3 != 0)) {
      uVar4 = (uint)CONCAT11((undefined1)local_8,local_8._1_1_);
    }
  }
  return uVar4;
}

// ====== 0x00870c42  FUN_00870c42 ======
byte * __cdecl FUN_00870c42(byte *param_1,byte *param_2)

{
  byte bVar1;
  byte *pbVar2;
  byte *pbVar3;
  
  if (DAT_009b411c == 0) {
    pbVar2 = FUN_00869f70(param_1,param_2);
    return pbVar2;
  }
  FUN_00860a61(0x19);
  bVar1 = *param_1;
  while (bVar1 != 0) {
    bVar1 = *param_2;
    pbVar2 = param_2;
    while (bVar1 != 0) {
      bVar1 = *pbVar2;
      if (((&DAT_009b4221)[bVar1] & 4) == 0) {
        pbVar3 = pbVar2;
        if (bVar1 == *param_1) break;
      }
      else if (((bVar1 == *param_1) && (pbVar2[1] == param_1[1])) ||
              (pbVar3 = pbVar2 + 1, pbVar2[1] == 0)) break;
      pbVar2 = pbVar3 + 1;
      bVar1 = *pbVar2;
    }
    if ((*pbVar2 != 0) ||
       ((((&DAT_009b4221)[*param_1] & 4) != 0 && (param_1 = param_1 + 1, *param_1 == 0)))) break;
    param_1 = param_1 + 1;
    bVar1 = *param_1;
  }
  FUN_00860ac2(0x19);
  return (byte *)(-(uint)(*param_1 != 0) & (uint)param_1);
}

// ====== 0x00870cd7  FUN_00870cd7 ======
byte * __cdecl FUN_00870cd7(byte *param_1,byte *param_2)

{
  byte *pbVar1;
  
  if (param_1 < param_2) {
    if (DAT_009b411c == 0) {
      pbVar1 = param_2 + -1;
    }
    else {
      FUN_00860a61(0x19);
      pbVar1 = param_2 + -1;
      if (((&DAT_009b4221)[param_2[-1]] & 4) == 0) {
        do {
          pbVar1 = pbVar1 + -1;
          if (pbVar1 < param_1) break;
        } while (((&DAT_009b4221)[*pbVar1] & 4) != 0);
        FUN_00860ac2(0x19);
        pbVar1 = param_2 + (-1 - ((int)param_2 - (int)pbVar1 & 1U));
      }
      else {
        FUN_00860ac2(0x19);
        pbVar1 = param_2 + -2;
      }
    }
  }
  else {
    pbVar1 = (byte *)0x0;
  }
  return pbVar1;
}

// ====== 0x00870d44  FUN_00870d44 ======
size_t __cdecl
FUN_00870d44(LCID param_1,uint param_2,LPCWSTR param_3,int param_4,LPWSTR param_5,size_t param_6,
            UINT param_7)

{
  int iVar1;
  size_t sVar2;
  int iVar3;
  void *local_14;
  undefined1 *puStack_10;
  undefined *puStack_c;
  undefined4 local_8;
  
  local_8 = 0xffffffff;
  puStack_c = &DAT_0089df68;
  puStack_10 = &LAB_0085fed0;
  local_14 = ExceptionList;
  ExceptionList = &local_14;
  if (DAT_009b3e30 == 0) {
    ExceptionList = &local_14;
    iVar1 = LCMapStringW(0,0x100,(LPCWSTR)&lpSrcStr_0089b9cc,1,(LPWSTR)0x0,0);
    if (iVar1 == 0) {
      iVar1 = LCMapStringA(0,0x100,(LPCSTR)&lpSrcStr_0089b9c8,1,(LPSTR)0x0,0);
      if (iVar1 == 0) {
        ExceptionList = local_14;
        return 0;
      }
      DAT_009b3e30 = 2;
    }
    else {
      DAT_009b3e30 = 1;
    }
  }
  if (0 < param_4) {
    param_4 = FUN_00870f4d(param_3,param_4);
  }
  if (DAT_009b3e30 == 1) {
    sVar2 = LCMapStringW(param_1,param_2,param_3,param_4,param_5,param_6);
    ExceptionList = local_14;
    return sVar2;
  }
  if (DAT_009b3e30 == 2) {
    if (param_7 == 0) {
      param_7 = CodePage_009b3a78;
    }
    iVar1 = WideCharToMultiByte(param_7,0x220,param_3,param_4,(LPSTR)0x0,0,(LPCSTR)0x0,(LPBOOL)0x0);
    if (iVar1 != 0) {
      local_8 = 0;
      FUN_0085f3a0();
      local_8 = 0xffffffff;
      if ((&stack0x00000000 != (undefined1 *)0x3c) &&
         (iVar3 = WideCharToMultiByte(param_7,0x220,param_3,param_4,&stack0xffffffc4,iVar1,
                                      (LPCSTR)0x0,(LPBOOL)0x0), iVar3 != 0)) {
        sVar2 = LCMapStringA(param_1,param_2,&stack0xffffffc4,iVar1,(LPSTR)0x0,0);
        if (sVar2 != 0) {
          local_8 = 1;
          FUN_0085f3a0();
          local_8 = 0xffffffff;
          if ((&stack0x00000000 != (undefined1 *)0x3c) &&
             (iVar1 = LCMapStringA(param_1,param_2,&stack0xffffffc4,iVar1,&stack0xffffffc4,sVar2),
             iVar1 != 0)) {
            if ((param_2 & 0x400) != 0) {
              if (param_6 != 0) {
                if ((int)sVar2 <= (int)param_6) {
                  param_6 = sVar2;
                }
                _strncpy((char *)param_5,&stack0xffffffc4,param_6);
                ExceptionList = local_14;
                return sVar2;
              }
              ExceptionList = local_14;
              return sVar2;
            }
            if (param_6 == 0) {
              param_6 = 0;
              param_5 = (LPWSTR)0x0;
            }
            sVar2 = MultiByteToWideChar(param_7,1,&stack0xffffffc4,sVar2,param_5,param_6);
            if (sVar2 != 0) {
              ExceptionList = local_14;
              return sVar2;
            }
          }
        }
      }
    }
  }
  ExceptionList = local_14;
  return 0;
}

// ====== 0x00870f4d  FUN_00870f4d ======
int __cdecl FUN_00870f4d(short *param_1,int param_2)

{
  short *psVar1;
  int iVar2;
  
  psVar1 = param_1;
  iVar2 = param_2;
  if (param_2 != 0) {
    do {
      iVar2 = iVar2 + -1;
      if (*psVar1 == 0) break;
      psVar1 = psVar1 + 1;
    } while (iVar2 != 0);
  }
  if (*psVar1 == 0) {
    return (int)psVar1 - (int)param_1 >> 1;
  }
  return param_2;
}
